### ISSUE TITLE
Unit of `Value` for `contract transaction` 

### ISSUE THREAD

**Issue by jennijuju** [satran004/aion4j-idea-plugin#12]
It would be nice if in the `contract transaction` pop up window, user can input their value in `Aion` and we automatically convert it to `nAmp`. (like deployment`)

**Comment by satran004** [comment]
Thanks. I will change that.

**Comment by satran004** [comment]
https://github.com/bloxbean/aion4j-idea-plugin/commit/a382b85f546d14dddd4ce70ae731e98882e3597c
