### ISSUE TITLE
Check status for deployment

### ISSUE THREAD

**Issue by jennijuju** [satran004/aion4j-idea-plugin#15]
When using Intellij plugin - Deploy, if a transaction is mined, it will show the receipt and `Build Success`(cuz the jar was built first.) 

However, it can be confusing when the deployment actually fails(status 0x0). Also, for us when a contract deployment fails, there is still a contract address in the receipt, so its really hard to notice the failure. Is it possible for us to add some sort of check for that and add a warning for user when it fails?

**Comment by satran004** [comment]
Yes, we can add a check on the status for 0x0 and show the notification for failure. This might be applicable for maven plugin also, right ?

**Comment by satran004** [comment]
This has already been fixed in maven plugin. So it should work now in IDEA  with latest maven plugin (0.7.2)
